name: Tests

on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NODE_ENV: test
      PORT: 3000
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: transfeera
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: transfeera_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.13.1"
          architecture: "x64"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Apply migrations
        run: npm run migrate
      - name: Run Tests
        run: npm run test
